/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stratego_marvel_proyecto_final;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author David
 */
public class SeleccionJugadores extends javax.swing.JFrame {

    
    ListaJugadores jugadoresActivos = DatosGlobales.listaJugadores;//quiza algo inecesario, si veo que sirve sin esto, se quita
    int cantPlayersActivos= jugadoresActivos.cantidad();
    //String playersActivos[]= new String[cantPlayersActivos];

    
    
    /**
     * Creates new form SeleccionJugadores
     */
    public SeleccionJugadores() {
        
        initComponents();
        NormalPanelConfig.configuracion(this);
        setLocationRelativeTo(null);

        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                FrmMenuPrincipal backmenu = new FrmMenuPrincipal();
                backmenu.setVisible(true);
                SeleccionJugadores.this.dispose();
            }
        });
        
        jcontricantes.removeAllItems();
        for(int i=0; i<cantPlayersActivos; i++){//Obtengo el nombre de todos los usuarios activos
            Jugador playertemp= jugadoresActivos.obtener(i);
            String nameHost= DatosGlobales.jugadorHost.getUsuario();
            String nameCont= playertemp.getUsuario();
            if(nameCont.equals(nameHost)){//Verificador para no agregar el nombre del Host
                //Salta el nombre del Host
            }else{
                 jcontricantes.addItem(nameCont);
            }
         jbandos.removeAllItems();
         jbandos.addItem("HEROES");
         jbandos.addItem("VILLANOS");
           
         
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        jcontricantes = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jbandos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Elija un Contricante");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Elija un Bando");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 190, 40));

        btnJugar.setBackground(new java.awt.Color(255, 255, 255));
        btnJugar.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(0, 0, 0));
        btnJugar.setText("Jugar");
        btnJugar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnJugar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 180, 60));

        jcontricantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcontricantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 170, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Elija un Contricante");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 190, 40));

        jbandos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jbandos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/backgroundContricante.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        String playerSeleccionado= (String) jcontricantes.getSelectedItem();
        Jugador playerTemp = jugadoresActivos.obtenerbyName(playerSeleccionado);
        DatosGlobales.jugadorContricante= playerTemp;
        String eleccion= (String) jbandos.getSelectedItem();
        if(eleccion.equals("HEROES")){
            DatosGlobales.jugadorHeroe = DatosGlobales.jugadorHost;
            DatosGlobales.jugadorVillian= DatosGlobales.jugadorContricante;
            System.out.println(DatosGlobales.jugadorHeroe.getUsuario());
            System.out.println(DatosGlobales.jugadorVillian.getUsuario());
        }else if(eleccion.equals("VILLANOS")){
            DatosGlobales.jugadorVillian= DatosGlobales.jugadorHost;
            DatosGlobales.jugadorHeroe= DatosGlobales.jugadorContricante;
            System.out.println(DatosGlobales.jugadorHeroe.getUsuario());
            System.out.println(DatosGlobales.jugadorVillian.getUsuario());
            
        }
        System.out.println("Contricante sera: "+playerSeleccionado);
        System.out.println(playerTemp);
        new FrmPartida().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionJugadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jbandos;
    private javax.swing.JComboBox<String> jcontricantes;
    // End of variables declaration//GEN-END:variables
}
